on:
  push:
    branches:
      - main
jobs:
  linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Submodules
        run: git submodule update --init --recursive
      - name: Clone dependency repository
        run: git clone https://github.com/effekseer/Effekseer --depth 1 ../Effekseer
      - name: Build binaries
        run: |
          cd ./Dev/Cpp
          sudo apt-get install scons
          sudo apt-get install gcc-multilib
          sudo apt-get install g++-multilib
          python3 build.py platform=linux
      - name: Upload binaries
        uses: actions/upload-artifact@v1
        with:
          name: bin_linux
          path: ./Dev/Godot/addons/effekseer/bin

  android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Submodules
        run: git submodule update --init --recursive
      - name: Clone dependency repository
        run: git clone https://github.com/effekseer/Effekseer --depth 1 ../Effekseer
      - name: Build binaries
        run: |
          cd ./Dev/Cpp
          sudo apt-get install scons
          python3 build.py platform=android
      - name: Upload binaries
        uses: actions/upload-artifact@v1
        with:
          name: bin_android
          path: ./Dev/Godot/addons/effekseer/bin

  macos:
    name: Build for macOS
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Update Submodules
        run: git submodule update --init --recursive
      - name: Clone dependency repository
        run: git clone https://github.com/effekseer/Effekseer --depth 1 ../Effekseer
      - name: Build binaries
        run: |
          cd ./Dev/Cpp
          brew install scons
          python3 build.py platform=osx
      - name: Upload binaries
        uses: actions/upload-artifact@v1
        with:
          name: bin_macos
          path: ./Dev/Godot/addons/effekseer/bin

  ios:
    name: Build for iOS
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Update Submodules
        run: git submodule update --init --recursive
      - name: Clone dependency repository
        run: git clone https://github.com/effekseer/Effekseer --depth 1 ../Effekseer
      - name: Build binaries
        run: |
          cd ./Dev/Cpp
          brew install scons
          python3 build.py platform=ios
      - name: Upload binaries
        uses: actions/upload-artifact@v1
        with:
          name: bin_ios
          path: ./Dev/Godot/addons/effekseer/bin

  windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Submodules
        run: git submodule update --init --recursive
      - name: Clone dependency repository
        run: git clone https://github.com/effekseer/Effekseer --depth 1 ../Effekseer
      - name: Build binaries
        run: |
          cd ./Dev/Cpp
          python -m pip install scons
          python build.py platform=windows
        shell: cmd
      - name: Upload binaries
        uses: actions/upload-artifact@v1
        with:
          name: bin_windows
          path: ./Dev/Godot/addons/effekseer/bin

  merge:
    name: Merge 
    runs-on: ubuntu-latest
    needs: [linux, android, macos, ios, windows]
    steps:
      - uses: actions/checkout@v2

      - name: Download Linux binaries
        uses: actions/download-artifact@v1
        with:
          name: bin_linux

      - name: Download Android binaries
        uses: actions/download-artifact@v1
        with:
          name: bin_android

      - name: Download macOS binaries
        uses: actions/download-artifact@v1
        with:
          name: bin_macos

      - name: Download iOS binaries
        uses: actions/download-artifact@v1
        with:
          name: bin_ios

      - name: Download Windows binaries
        uses: actions/download-artifact@v1
        with:
          name: bin_windows

      - name: Copy binaries
        run: |
          mkdir ./Dev/Godot/addons/effekseer/bin
          cp -r bin_linux/linux ./Dev/Godot/addons/effekseer/bin/
          cp -r bin_android/android ./Dev/Godot/addons/effekseer/bin/
          cp -r bin_macos/osx ./Dev/Godot/addons/effekseer/bin/
          cp -r bin_ios/ios ./Dev/Godot/addons/effekseer/bin/
          cp -r bin_windows/windows ./Dev/Godot/addons/effekseer/bin/

      - name: Upload built package
        uses: actions/upload-artifact@v1
        with:
          name: addons
          path: ./Dev/Godot/addons
